version: '3.5'

services:
  load-consumer:
    build: .
    command: npm run start:prod
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3300:3300"
      - "3301:3301"
      - "3302:3302"
      - "3303:3303"
    networks:
      - server_load_balancer

networks:
  server_load_balancer:
    external: true
